2019-09-24 19:38:56,238-6d  ERROR    work.segmentation.clarifruit_segmentation.image: Failed reading mask: D:\Clarifruit\cherry_stem\data\raw_data\stem classes\label\raw_masks\A.PNG
Traceback (most recent call last):
  File "D:\Clarifruit\cherry_stem\work\segmentation\clarifruit_segmentation\image.py", line 67, in read_img
    raise ReadImageException(error_message, path)
work.segmentation.clarifruit_segmentation.exceptions.ReadImageException: ("Can't read mask from", 'D:\\Clarifruit\\cherry_stem\\data\\raw_data\\stem classes\\label\\raw_masks\\A.PNG')
2019-09-24 19:39:42,679-6d  ERROR    work.segmentation.clarifruit_segmentation.image: Failed reading mask: D:\Clarifruit\cherry_stem\data\raw_data\stem classes\label\raw_masks\A.PNG
Traceback (most recent call last):
  File "D:\Clarifruit\cherry_stem\work\segmentation\clarifruit_segmentation\image.py", line 67, in read_img
    raise ReadImageException(error_message, path)
work.segmentation.clarifruit_segmentation.exceptions.ReadImageException: ("Can't read mask from", 'D:\\Clarifruit\\cherry_stem\\data\\raw_data\\stem classes\\label\\raw_masks\\A.PNG')
2019-09-24 19:40:50,515-6d  ERROR    work.segmentation.clarifruit_segmentation.image: Failed reading mask: D:\Clarifruit\cherry_stem\data\raw_data\stem classes\label\raw_masks\A.PNG
Traceback (most recent call last):
  File "D:\Clarifruit\cherry_stem\work\segmentation\clarifruit_segmentation\image.py", line 67, in read_img
    raise ReadImageException(error_message, path)
work.segmentation.clarifruit_segmentation.exceptions.ReadImageException: ("Can't read mask from", 'D:\\Clarifruit\\cherry_stem\\data\\raw_data\\stem classes\\label\\raw_masks\\A.PNG')
2019-09-25 17:04:30,399-6d  ERROR    work.auxiliary.image: Failed reading mask: D:\Clarifruit\cherry_stem\data\raw_data\stem classes\ground\D\label\72157-48926.png.jpg
Traceback (most recent call last):
  File "D:\Clarifruit\cherry_stem\work\auxiliary\image.py", line 68, in read_img
    raise ReadImageException(error_message, path)
work.segmentation.clarifruit_segmentation.exceptions.ReadImageException: ("Can't read mask from", 'D:\\Clarifruit\\cherry_stem\\data\\raw_data\\stem classes\\ground\\D\\label\\72157-48926.png.jpg')
2019-09-25 17:05:23,194-6d  ERROR    work.auxiliary.image: Failed reading mask: D:\Clarifruit\cherry_stem\data\raw_data\stem classes\ground\D\label\72157-48926.png.jpg
Traceback (most recent call last):
  File "D:\Clarifruit\cherry_stem\work\auxiliary\image.py", line 68, in read_img
    raise ReadImageException(error_message, path)
work.segmentation.clarifruit_segmentation.exceptions.ReadImageException: ("Can't read mask from", 'D:\\Clarifruit\\cherry_stem\\data\\raw_data\\stem classes\\ground\\D\\label\\72157-48926.png.jpg')
2019-10-07 18:52:32,962-6d  ERROR    auxiliary.custom_image: Failed reading mask from: D:\Clarifruit\cherry_stem\data\unet_data\training\2019-09-30_07-19-46\test\A\38360-00777.png.npy
Traceback (most recent call last):
  File "D:\Clarifruit\Clarifruit_functions\auxiliary\custom_image.py", line 80, in read_raw_pred
    pred = np.load(self.mask_path, allow_pickle=True)
  File "D:\Clarifruit\cherry_stem\cherry_venv\lib\site-packages\numpy\lib\npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Clarifruit\\cherry_stem\\data\\unet_data\\training\\2019-09-30_07-19-46\\test\\A\\38360-00777.png.npy'
2019-10-07 22:24:25,132-6d  ERROR    auxiliary.custom_image: Failed reading mask from: D:\Clarifruit\cherry_stem\data\unet_data\training\2019-10-07_20-12-39\raw_pred\38357-02789.png.npy
Traceback (most recent call last):
  File "D:\Clarifruit\Clarifruit_functions\auxiliary\custom_image.py", line 80, in read_raw_pred
    pred = np.load(self.mask_path, allow_pickle=True)
  File "D:\Clarifruit\cherry_stem\cherry_venv\lib\site-packages\numpy\lib\npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Clarifruit\\cherry_stem\\data\\unet_data\\training\\2019-10-07_20-12-39\\raw_pred\\38357-02789.png.npy'
2019-10-11 12:31:34,410-6d  ERROR    auxiliary.custom_image: Failed reading mask from: D:\Clarifruit\cherry_stem\data\unet_data\training\2019-10-07_20-12-39\test\A\38360-03505.png.npy
Traceback (most recent call last):
  File "D:\Clarifruit\Clarifruit_functions\auxiliary\custom_image.py", line 80, in read_raw_pred
    pred = np.load(self.mask_path, allow_pickle=True)
  File "D:\Clarifruit\cherry_stem\cherry_venv\lib\site-packages\numpy\lib\npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Clarifruit\\cherry_stem\\data\\unet_data\\training\\2019-10-07_20-12-39\\test\\A\\38360-03505.png.npy'
